### ISSUE TITLE
浏览器无法访问并且报错

### ISSUE THREAD

**Issue by JustRushHour** [ZYunfeii/ElegantWebServer#2]
输入ip:端口号后网页显示该网页无法正常运作

小白想学习一下可是一直运行不成功/(ㄒoㄒ)/~~

![报错](https://user-images.githubusercontent.com/88029078/233533058-04011e8c-6a4b-49ab-9262-e2f6bbee0901.png)
![日志](https://user-images.githubusercontent.com/88029078/233533066-71e7dbd9-143f-487e-a75f-4e1d187a4771.png)

**Comment by ZYunfeii** [comment]
尝试用一下deploy分支的代码试试

**Comment by JustRushHour** [comment]
还是不行/(ㄒoㄒ)/~~
deploy分支的代码偶尔可以进去前端页面
我把代码拉到我的云服务器修改main.cpp中的Mysql配置后执行了以下命令：
cd build
cmake ..
make
cd
redis-server ./code/redis/redis.conf
./build/server
然后通过浏览器进行访问
我的步骤有问题吗大佬/(ㄒoㄒ)/~~

**Comment by JustRushHour** [comment]
还是不行/(ㄒoㄒ)/~~
deploy分支的代码偶尔可以进去前端页面
我把代码拉到我的云服务器修改main.cpp中的Mysql配置后执行了以下命令：
cd build
cmake ..
make
cd
redis-server ./code/redis/redis.conf
./build/server
然后通过浏览器进行访问
我的步骤有问题吗大佬/(ㄒoㄒ)/~~

**Comment by ZYunfeii** [comment]
报错提示就上述那么简单么

**Comment by JustRushHour** [comment]
> 

是的，报错始终是这个，偶尔能进入前端页面，但是进入其他页面或者稍等一会后还是会报相同的错误。
我尝试运行mark大佬的项目，似乎并没有问题。

**Comment by JustRushHour** [comment]
尝试修改redisFile_ = rc->getKeyVal(path_);
为 redisFile_ = noStr;
后问题解决
不过我还想弱弱的问一下文件上传后上传到了哪里呀/(ㄒoㄒ)/~~

**Comment by ZYunfeii** [comment]
有一个文件夹里面有上传的文件，不过目前比较大的文件上传有小问题

**Comment by JustRushHour** [comment]
> 有一个文件夹里面有上传的文件，不过目前比较大的文件上传有小问题

我上传文件后并未在代码目录下的文件夹里找到相应文件，我再试试
