### ISSUE TITLE
关于压力测试

### ISSUE THREAD

**Issue by JustRushHour** [ZYunfeii/ElegantWebServer#3]
可以问一下您的压力测试QPS可以到达多少嘛？
我的测试环境是2核4G，QPS只有100多，没有开启redis

**Comment by ZYunfeii** [comment]
我这4 5千吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZYunfeii/ElegantWebServer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月30日(星期二) 中午1:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ZYunfeii/ElegantWebServer] 关于压力测试 (Issue #3)





 
可以问一下您的压力测试QPS可以到达多少嘛？
 我的测试环境是2核4G，QPS只有100多，没有开启redis
