### ISSUE TITLE
关于大文件上传代码的疑问

### ISSUE THREAD

**Issue by WestRiver6620** [ZYunfeii/ElegantWebServer#4]
你好，对于 code/http/httpconn.cpp 中的代码
`if(length != -1 && readBuff_.ReadableBytes() < length) return false;  // 解决大文件上传bug post传输大数据量时会分段发送 没接收完别处理`
我想 ‘readBuff_.ReadableBytes()’ 得到的应该是buff中存放的整个请求的长度，而 ‘length‘ 表示的是请求头中 ’content-length‘ 的值也就是请求体的长度，通过这两个值判断文件是否读完是否存在问题

**Comment by ZYunfeii** [comment]
你说的没错

**Comment by WestRiver6620** [comment]
> 你说的没错

谢谢你的回复，而且我发现上传后的图片虽然看起来没什么区别，但是两个文件的hash值是不同的，我认为问题可能出在第一个post请求体后面跟的并不是第二个post的请求体，而是整个请求报文，这部分被当作请求体的内容存储了

**Comment by ZYunfeii** [comment]
如果是你说的可能图片显示都会有问题，我不知道你是通过哪种方式计算文件哈希值的。我记得我是拿到的body进行增量添加的。

**Comment by WestRiver6620** [comment]
> 如果是你说的可能图片显示都会有问题，我不知道你是通过哪种方式计算文件哈希值的。我记得我是拿到的body进行增量添加的。

不好意思我明白了，并不是HTTP发送了多个请求来传输文件，而是TCP/IP层将数据进行切片了，所以需要多次读才能读全

**Comment by WestRiver6620** [comment]
会不会是除了第一个post请求，剩下的请求是没有请求头和请求行的，我在之前处理原项目的bug发现剩下的请求的请求和是一些乱码。

**Comment by ZYunfeii** [comment]
是的，tcp面向二进制流的，这里其实就是处理了tcp粘包问题，基于头字段做的。
